---
machine_hostname: desktop

sway_outputs:
  - name: DP-1
    resolution: 2560x1440
    refresh: 144
    position: "0 0"
  - name: DP-2
    resolution: 1920x1080
    refresh: 60
    position: "2560 0"
