---
- name: Bootstrap machine
  hosts: localhost
  become: false

  vars:
    dotfiles_dir: "{{ playbook_dir }}/.."
    home_dir: "{{ ansible_env.HOME }}"
    stow_dir: "{{ dotfiles_dir }}/stow"

  roles:
    - repos
    - packages
    - services
    - os-config
    - role: sway
      when: wm == "sway"
    - role: i3
      when: wm == "i3"
    - role: nvidia
      when: nvidia | bool
